baseURL = 'https://martincarapia.github.io/PortfolioSite/'
languageCode = 'en-us'
title = 'My Portfolio Site'
theme = 'basic'

[params]
  description = 'Welcome to my portfolio site'
  author = 'Richard Dawkins'
